version: "3.9"

services:
  backend:
    build: ./backend
    container_name: robot_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=robot_user
      - DATABASE_PASS=robotpass
      - DATABASE_NAME=robot_db
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: robot_db
    restart: always
    environment:
      POSTGRES_USER: robot_user
      POSTGRES_PASSWORD: robotpass
      POSTGRES_DB: robot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
